### ISSUE TITLE
[Request] Multiple API sources?

### ISSUE THREAD

**Issue by jpmurray** [WackyStudio/forge-ssh-assistant#1]
Hello,

I haven't dug into the code yet, I might be able to look at it and make a proposition later on but, would a way to add multiple API keys so we have multiple sources of servers? (Personally, I have access to my own Forge account and a client's, so that'd be handy!)

What would you think?

**Comment by ThomasNoergaard** [comment]
Hello,

That's a good idea and a feature we actually have planned for a future release.

Tokens are saved in an array in the config file, so it wouldn't be too hard to implement.

You are very welcome to make a proposition or else I will look into it as soon as I have time.

**Comment by jpmurray** [comment]
@ThomasNoergaard I'm playing with the code at the moment, I might have a proposal soon ;-)

**Comment by ThomasNoergaard** [comment]
Im closing this issue since it has been implemented in the pull request from @jpmurray
